"""Prepare Figure 9(a) web data without modifying the supplied experiment CSV.
Usage: python3 scripts/prepare-akv-data.py ../48c14-96c12-kv96c14.csv
"""
import csv
import json
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[1]
source = Path(sys.argv[1])
rows = list(csv.DictReader(source.open(encoding='utf-8-sig')))
methods = [('96kc12', 'Standard', 12, '#697384', '8 6'),
           ('48kc14', 'Text Engineering', 14, '#4488dc', '3 6'),
           ('kv96k c14', 'AKV', 14, '#9160e7', '')]
assert {r['group'] for r in rows} == {m[0] for m in methods}
series = []
for group, label, concurrency, color, dash in methods:
    runs = []
    for repeat in ('1', '2', '3'):
        selected = sorted((r for r in rows if r['group'] == group and r['repeat'] == repeat), key=lambda r: float(r['elapsed_seconds']))
        assert len(selected) == 102, (group, repeat, len(selected))
        assert int(selected[-1]['completed_cases']) == 100
        assert all(int(r['expected_cases']) == 100 for r in selected)
        assert all(float(r['elapsed_seconds']) >= 0 for r in selected)
        assert len({r['case_id'] for r in selected if r['event'] == 'case_completed'}) == 100
        for previous, current in zip(selected, selected[1:]):
            assert int(current['passed_cases']) >= int(previous['passed_cases'])
        runs.append({'repeat': int(repeat), 'points': [
            [float(r['elapsed_seconds']) * 8 / 3600, int(r['passed_cases']), int(r['completed_cases'])]
            for r in selected
        ]})
    series.append(dict(label=label, concurrency=concurrency, color=color, dash=dash, runs=runs))
output = root / 'projects/akv/static'
data = {'gpuCount': 8, 'expectedCases': 100, 'series': series}
(output / 'js/replay-data.js').write_text('// Generated by scripts/prepare-akv-data.py.\nwindow.AKV_REPLAY = ' + json.dumps(data, separators=(',', ':')) + ';\n')
# Keep public plot fields only. Internal server paths and execution IDs are not web assets.
fields = ['group', 'repeat', 'elapsed_seconds', 'elapsed_minutes', 'passed_cases',
          'completed_cases', 'expected_cases', 'event', 'original_elapsed_seconds', 'time_divisor']
with (output / 'data/figure-9a.csv').open('w', newline='') as f:
    writer = csv.DictWriter(f, fields, extrasaction='ignore')
    writer.writeheader()
    writer.writerows(rows)
print(f'Prepared {len(rows)} events across 9 runs. Final pass rates:')
for method in series:
    vals = [run['points'][-1][1] for run in method['runs']]
    print(method['label'], vals, 'mean', sum(vals) / len(vals))
